version: "3.3"
  
services:
  linebot:
    image: gary80221/linebotrelease
    ports:
      - "4000:4000"
    build: .
    env_file:
      - ./.env
    environment:      
      SSL_PEM : /run/secrets/SSL_PEM 
      SSL_KEY : /run/secrets/SSL_KEY      
    secrets:
      - SSL_PEM
      - SSL_KEY
    networks: 
      - mynet      
      
networks:
  mynet:
    driver: bridge

secrets:
  SSL_PEM:
    file: ./SSL_YiFanServer/yfnoip_ddns_net.pem-chain
  SSL_KEY: 
    file: ./SSL_YiFanServer/YiFanServer.Key
  
